/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10/samples
 */

group = "xyz.brandonirizarry"
version = "1.0"

plugins {
    application
    `maven-publish`
    id("org.barfuin.gradle.taskinfo") version "2.2.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "xyz.brandonirizarry.movesquarebackend.game.Game"
    mainModule = "xyz.brandonirizarry.moveSquareBackend"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            artifactId = "move-square-backend"
        }
    }
    repositories {
        maven {
            url = uri("https://maven.pkg.github.com/BrandonIrizarry/MoveSquareBackend")
            credentials {
                username = System.getenv("GITHUB_USER")
                password = System.getenv("GITHUB_PAT")
            }
        }
    }
}
